DROP USER IF EXISTS 'Admin'@'%';
CREATE USER IF NOT EXISTS 'Admin'@'%' IDENTIFIED BY 'Admin';

DROP SCHEMA IF EXISTS CONCIERTODB;
CREATE SCHEMA CONCIERTODB;

GRANT ALL ON CONCIERTODB.* TO 'Admin'@'%';
FLUSH PRIVILEGES;